<?php

include "Badge.php";
/**
 * Created by PhpStorm.
 * User: hamlet
 * Date: 4/10/17
 * Time: 1:24 PM
 */
class SpecialBadge extends Badge
{
    public function _construct($icon, $title, $info)
    {
        parent::_construct($icon, $title, $info); // TODO: Change the autogenerated stub
    }
}